# Generated by Django 3.1.3 on 2020-11-21 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_form', '0002_auto_20201121_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consists', models.TextField(max_length=255)),
                ('market', models.IntegerField(choices=[(0, 'Products'), (1, 'Services')])),
                ('industry', models.TextField(max_length=255)),
                ('classification', models.IntegerField(choices=[(0, 'Freelancer: I am a specialist in doing something and that is what I want to offer without the need to perform tasks in the different areas related to a company'), (1, 'Self-employment: the daily operation of my business will depend mainly on my working'), (2, 'Micro-company: I want to create a company that generates value through hired collaborators and my daily work (up to 10 employees)'), (3, 'Company: I want to create a company that generates value mainly through hired collaborators (more than 10 employees)'), (4, 'Company in need of investments: I want to create a company with investment partners because it requires (or required) a lot of capital'), (5, 'Other:')])),
                ('classification_detail', models.TextField(max_length=255, null=True)),
                ('time_spend', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Entrepreneurship',
        ),
        migrations.RenameModel(
            old_name='Email',
            new_name='FirstStep',
        ),
        migrations.AddField(
            model_name='secondstep',
            name='foreign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='survey_form.firststep'),
        ),
    ]
