# Generated by Django 3.1.3 on 2020-11-21 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_form', '0004_auto_20201121_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourthstep',
            name='foreign',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey_form.firststep'),
            preserve_default=False,
        ),
    ]
