# Generated by Django 3.1.3 on 2020-11-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_form', '0005_fourthstep_foreign'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fifthstep',
            name='foreign',
        ),
        migrations.RemoveField(
            model_name='fourthstep',
            name='foreign',
        ),
        migrations.RemoveField(
            model_name='secondstep',
            name='foreign',
        ),
        migrations.RemoveField(
            model_name='thirdstep',
            name='foreign',
        ),
        migrations.DeleteModel(
            name='FirstStep',
        ),
    ]
