# Generated by Django 3.1.3 on 2020-11-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_form', '0006_auto_20201121_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscreator',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
