# Generated by Django 3.1.3 on 2020-11-22 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey_form', '0007_auto_20201122_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscreator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesscreator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
