# Generated by Django 3.1.3 on 2020-11-22 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_form', '0008_auto_20201122_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondstep',
            name='co_creator',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey_form.businesscreator'),
            preserve_default=False,
        ),
    ]
