# Generated by Django 3.1.3 on 2020-11-22 04:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey_form', '0009_secondstep_co_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='fifthstep',
            name='co_creator',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey_form.businesscreator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fourthstep',
            name='co_creator',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey_form.businesscreator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thirdstep',
            name='co_creator',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey_form.businesscreator'),
            preserve_default=False,
        ),
    ]
